### ISSUE TITLE
Raspberry Pi 3 crash when performing 'catkin_make'

### ISSUE THREAD

**Issue by BrrrIce** [leggedrobotics/xpp#6]
In ROS kinetic, at about 80% after the `catkin_make -DCMAKE_BUILD_TYPE=Release` command is sent UbuntuMATE stops responding forcing a hard shut down. The only changes from ROS being installed is doing the ROS tutorial and downloading the pre-compiled version of Xpp.

**Comment by awinkler** [comment]
Hi @BrrrIce 
Could you kindly post some log or console output before it crashes so we can investigate this further. Thanks!
